from src.basemodels import FunctionDefinition
from enum import Enum
import re


class ParamType(Enum):
    """Enum for parameter types"""
    NUMBER = "number"
    STRING = "string"
    BOOL = "boolean"
    INTEGER = "integer"
    FLOAT = "float"


class CandidateStatus(Enum):
    """Enum for candidate status"""
    VALID_COMPLETE = "valid_complete"
    VALID_PREFIX = "valid_prefix"
    INVALID = "invalid"


def check_candidate_logits(
        candidate: str, allowed: list[str]
        ) -> CandidateStatus:
    """
    Check if a candidate is valid or not
    Args:
        candidate: str: the candidate to check
        allowed: list[str]: the list of allowed candidates
    Returns:
        CandidateStatus: the status of the candidate
    """
    for function_name in allowed:
        if candidate == function_name:
            return CandidateStatus.VALID_COMPLETE
        elif function_name.startswith(candidate):
            return CandidateStatus.VALID_PREFIX
    return CandidateStatus.INVALID


def is_bool(value: str) -> bool:
    """
    Check if a candidate is a valid boolean
    Args:
        value: str: the candidate to check
    Returns:
        bool: True if the candidate is a valid boolean, False otherwise
    """
    if value in ['False', 'True']:
        return True
    return False


def find_stop_char(token_text: str) -> str | None:
    """
    Find the first stop character in a token text
    Args:
        token_text: str: the token text to check
    Returns:
        str | None: the first stop character found, or None if no stop
        character is found
    """
    for i, char in enumerate(token_text):
        if (
            char == 'Ċ' or
            char == '"' or
            ord(char) < 0x20
                ):
            return token_text[:i]  # lo que hay antes del carácter de corte
    return None  # no hay carácter de corte, todo el token es válido


def build_context_for_fn_name(
        functions: list[FunctionDefinition], prompt: str
        ) -> str:
    """
    Build the context for the function name selection
    Args:
        functions: list[FunctionDefinition]: the list of function definitions
        prompt: str: the user prompt
    Returns:
        str: the context for the function name selection
    """
    functions_text = "\n".join(
            f"- {f.name}: {f.description}" for f in functions)
    context: str = (
        f"check function definition {functions_text} and"
        f"return a function name that solve this request: {prompt}."
        "Answer: "
        )
    return context


def build_context_for_parameter(
        prompt: str, function: FunctionDefinition
        ) -> str:
    """
    Build the context for the parameter selection
    Args:
        prompt: str: the user prompt
        function: FunctionDefinition: the function definition
    Returns:
        str: the context for the parameter selection
    """
    fn_name: str = function.name
    fn_description: str = function.description
    context: str = (
        'Selected function:\n'
        f'{fn_name}\n'
        f'Description:\n'
        f'{fn_description}\n'
        f'Parameters:\n'
    )
    for p_name, p_definition in function.parameters.items():
        context += f"- {p_name}: {p_definition.type}\n"
    context += (
        f'Request "{prompt}"\n'
        'Return a function call in JSON format with keys "name"'
        'and "parameters".\n'
        'Preserve the original spelling, capitalization, punctuation, '
        'and formatting of parameter values from the user request unless '
        'a transformation is explicitly requested.\n'
        f'\n{{"name": "{fn_name}", "parameters": {{'
    )
    return context


def preserve_literal_string_value(
    value: str,
    user_prompt: str
) -> str:
    """
    Preserve the exact text formatting of a generated string value.

    The function searches the original user prompt for a unique
    case-insensitive match of the generated value. If exactly one match
    is found, the original spelling and capitalization from the prompt
    are returned. Otherwise, the generated value is left unchanged.

    Args:
        value: String value generated by the model.
        user_prompt: Original natural-language request from the user.

    Returns:
        The matching text from the original prompt when a unique match
        exists, otherwise the original generated value.
    """
    if not value:
        return value
    pattern = re.escape(value)
    if value[0].isalnum():
        pattern = r"\b" + pattern
    if value[-1].isalnum():
        pattern = pattern + r"\b"
    matches = list(
        re.finditer(
            pattern,
            user_prompt,
            flags=re.IGNORECASE
        )
    )
    if len(matches) == 1:
        return matches[0].group(0)
    return value


def clean_param_value(text: str) -> str:
    """Clean spaces and ' from the string"""
    clean_spaces = text.strip()
    return re.sub(r'\\+', r'\\', clean_spaces)


def clean_number(text: str) -> str:
    """Clean .000 from numbers"""
    clean: str = text.rstrip('0').rstrip('.')
    return clean
